<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 
<br>
<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>
<center> <h1>Curso:</h1> </center>
<center> <h1>Computación 2</h1> </center>
<br>
<center> <h2>Docentes:</h2> </center>
<center> <h2>Ing. Renzo Bolivar</h2> </center>
<br>
<center> <h2>Tema:</h2> </center>
<center> <h2>Numpy I</h2> </center>
<br>
<center> <h2>Alumno: </h2> </center>
<center> <h2>Cristhofer Alexis Saenz Gonzalez</h2> </center>
<br>
<br>

# Matrices en Numpy

### Matriz unidimensional

In [4]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


Con la primera instrucción import numpy as np le estamos indicando a nuestro programa de Python que de ahora en adelante np será la referencia para todo lo referente a NumPy

### Matriz bidimensional

In [8]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
array = np.array ([[10,20,30],[40,50,60]] , dtype = np.int64)
print (array)

[[10 20 30]
 [40 50 60]]


### Porque usar NumPy

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

### Cantidad de memoria asignada 

In [11]:
import sys
S = range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [13]:
D = np.arange(1000)
print(D.size*D.itemsize)

8000


### Velocidad

In [16]:
import time

SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)

start = time.time()
result = [(x,y) for x,y in zip (L1,L2)] #se usa for 
print ((time.time()-start)*1000) #velocidad en listas

397.05681800842285


In [17]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

Start = time.time()
result = A1 + A2                 ## solo se suma
print((time.time()-start)*1000) ##Velocidad de Numpy


144315.19603729248


## Matrices Vacias

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.

Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

#### Crear una matriz en donde todos los valores sean igual a 1



In [28]:
uno = np.ones((3,10))
print(uno)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Crear una matriz en donde todos los valores sean igual a 0

In [27]:
cero = np.zeros((8,4))
print(cero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Crear una matriz de números aleatorios

In [24]:
al = np.random.random((8,5))
print(al)

[[0.38860566 0.56213008 0.66063778 0.89356143 0.52272085]
 [0.72000568 0.25087658 0.85938354 0.59898659 0.4328157 ]
 [0.26695077 0.12300811 0.21951175 0.70992122 0.77084749]
 [0.14990142 0.4813619  0.31553619 0.26269775 0.47826858]
 [0.05115373 0.40719353 0.21732521 0.42324723 0.00370084]
 [0.38408418 0.46643916 0.50995576 0.0141796  0.4331089 ]
 [0.44084199 0.00394089 0.05263986 0.3800599  0.25358749]
 [0.84590508 0.64880271 0.57963822 0.46504049 0.32840535]]


#### Crear una matriz vacía

In [35]:
vacio = np.empty((3,2))
print(vacio) 

[[4.64187906e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


#### Crear una matriz que contenga un solo valor en todas las posiciones

In [33]:
full = np.full((5,5),10)
print(full)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


#### Crear una matriz con rangos de números

In [37]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [39]:
a2 = np.linspace(10,100,10)
print(a2)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


##### Crear una matriz identidad

In [40]:
iden = np.eye(4,4)
print(iden)

iden2 = np.identity(4)
print(iden2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Inspeccionar matrices de NumPy

#### Dimensión de una matriz

In [55]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(A.ndim)

2


#### Tipo de Datos de una matriz

In [50]:
print(A.dtype)

int64


#### Tamaño y forma de una matriz

In [53]:
b = np.array([(15,2,35,45,55,65,75,85,95)])
print(b.size)
print(b.shape)

9
(1, 9)


#### Cambio de forma de una matriz

In [61]:
c = np.array ([(1,2,3),(2,3,1)])
print(c)
c = c.reshape(3,2)
print(c)

[[1 2 3]
 [2 3 1]]
[[1 2]
 [3 2]
 [3 1]]


#### Seleccionar elemento de una matriz

In [64]:
x = np.array([(10,20,30),(15,25,35)])
print(x[0,2])

30


In [68]:
a = np.array([(9,8,7,6),(1,2,3,4)])
print(a[0:,3])

[6 4]


# Operaciones Matemáticas entre matrices de NumPy

#### Valor mínimo, máximo y la suma de una matriz

In [73]:
a = np.array ([(10,80,100)])
print(a.min())
print(a.max())
print(a.sum())

10
100
190


#### Raiz Cuadrada y Desviación de una matriz

In [74]:
a = np.array([(2,4,6),(8,10,12)])
print(np.sqrt(a))
print(np.std(a))

[[1.41421356 2.         2.44948974]
 [2.82842712 3.16227766 3.46410162]]
3.415650255319866


#### Suma, resta, multiplicación y división de dos matrices

In [77]:
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)
print()

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]



## Ejemplos

Ejemplo 1: Cree una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal

In [43]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Ejemplo 2: Crea un vector aleatorio de tamaño 30 y encuentra el valor medio 

In [44]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5531328031492329


Ejemplo 3: ¿Cómo ordenar una matriz por la enésima columna?

In [45]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 3 7]
 [3 1 3]
 [5 4 7]]
[[3 1 3]
 [4 3 7]
 [5 4 7]]


Ejemplo 4: ¿Cómo agregar un borde (lleno de 0) alrededor de una matriz existente?

In [46]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
