# EJERCICIOS

### Ejercicio 01

Crear un array 7x8 lleno de ceros de tipo entero

In [3]:
import numpy as np

a = np.array([(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0)])
print(a)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.

In [14]:
b = np.array([(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0),(1,0,0,0,0,0,0)])
print(b)

[[1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]


Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [14]:
c = np.array([(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(0,0,0,0,0,0,0),(5,5.5,6,6.5,7,7.5,7.9)])

print(c)


[[0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [5.  5.5 6.  6.5 7.  7.5 7.9]]
